#==================== Tomcat Setting =====================#
server:
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
  port: 9081
#==================== spring Setting =====================#
spring:
  datasource:
    druid:
      username: root
      password: 123456a
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ojdbtest?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      max-active: 50
      min-idle: 10
      initial-size: 10
      max-wait: 10
      default-auto-commit: true
  http:
    encoding:
      charset: UTF-8
mybatis:
  config-location: classpath:mybatis.config.xml
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.oj.judge.entity

#==================== logging Setting =====================#
#logging:
#  config: classpath:logback.xml

#==================== project Setting  =====================#
file:
  server:
    dir: /Users/dengsuyuan/Downloads/test
    testcase:
      dir: ${file.server.dir}/testcase
#====================rocketMQ Setting =====================#
rocketmq:
  nameserver: 39.106.134.120:9876
  topic: ojcode
  consumer:
    group: judgeConsumerGroup
    max-thread: 20
    min-thread: 10